site_name: react-jsonschema-form documentation
docs_dir: docs
theme: readthedocs

nav:
  - Introduction: index.md
  - Advanced Customization: advanced-customization.md
  - Definitions: definitions.md
  - Dependencies: dependencies.md
  - Form Customization: form-customization.md
  - Theme Customization: theme-customization.md
  - Validation: validation.md
  - Playground: https://rjsf-team.github.io/react-jsonschema-form/

markdown_extensions:
  - toc:
      permalink: true
